version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: ../build/app/Dockerfile
    volumes:
      - ./app:/app
      - app_modules:/app/deps
      - app_modules:/app/_build
    ports:
      - 4000:4000
    tty: true
    depends_on:
      db:
          condition: service_healthy
    command: >
      bash -c "
        mix deps.get && mix deps.compile &&
        mix ecto.create && mix ecto.migrate && 
        mix phx.server"
    
  db:
    build:
      context: ./build/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  app_modules:
