name: Run Tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@4

      - name: Start Application
        run: |
          docker-compose up -d
          until curl -s localhost:4000; do sleep 5; done
      - name: Run Tests
        run: docker-compose exec -T app mix test